language: cpp

compiler:
  - gcc
  - clang

env:
  - GLIBCXX_DEBUG=1
  - NO_GLIBCXX_DEBUG=1

before_install:
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository --yes ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost1.54-all-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
  - rake test
